// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr6Irvg-YXx-Px9OTPdwzRPG7VEPXoJ78',
    appId: '1:1072996665171:web:4eaae8d7321726ffca83a6',
    messagingSenderId: '1072996665171',
    projectId: 'yakkit-abcf9',
    authDomain: 'yakkit-abcf9.firebaseapp.com',
    storageBucket: 'yakkit-abcf9.firebasestorage.app',
    measurementId: 'G-XHPZQKPRFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Xv5TW9a6dALpMeMErb6L2Yi8Sa1MK5Q',
    appId: '1:1072996665171:android:89732901c1ed83bfca83a6',
    messagingSenderId: '1072996665171',
    projectId: 'yakkit-abcf9',
    storageBucket: 'yakkit-abcf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnERZ9FpS2Aenuu2_XYaIWVuHycwzimXo',
    appId: '1:1072996665171:ios:ab90b200c570a608ca83a6',
    messagingSenderId: '1072996665171',
    projectId: 'yakkit-abcf9',
    storageBucket: 'yakkit-abcf9.firebasestorage.app',
    iosBundleId: 'com.example.yakkitCalorieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnERZ9FpS2Aenuu2_XYaIWVuHycwzimXo',
    appId: '1:1072996665171:ios:ab90b200c570a608ca83a6',
    messagingSenderId: '1072996665171',
    projectId: 'yakkit-abcf9',
    storageBucket: 'yakkit-abcf9.firebasestorage.app',
    iosBundleId: 'com.example.yakkitCalorieTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr6Irvg-YXx-Px9OTPdwzRPG7VEPXoJ78',
    appId: '1:1072996665171:web:6b3bae65bbce2cfeca83a6',
    messagingSenderId: '1072996665171',
    projectId: 'yakkit-abcf9',
    authDomain: 'yakkit-abcf9.firebaseapp.com',
    storageBucket: 'yakkit-abcf9.firebasestorage.app',
    measurementId: 'G-GN9E8NQ9FX',
  );
}
